/*==============================================================================

name:       ReactGeneratedCode.java

purpose:    Will be autogenerated at compile time.

history:    Sat Jan 05, 2019 10:30:00 (Giavaneers - LBM) created

notes:
                        COPYRIGHT (c) BY GIAVANEERS, INC.
         This source code is licensed under the MIT license found in the
             LICENSE file in the root directory of this source tree.

==============================================================================*/
                                       // package --------------------------- //
package io.reactjava.client.core.react;
                                       // imports --------------------------- //
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import jsinterop.annotations.JsMethod;
                                       // ReactGeneratedCode =================//
public class ReactGeneratedCode
{
                                       // class constants --------------------//
public static final String kREACT_JAVA_DIR_NAME       = "reactjava";
public static final String kIMPORTED_STYLESHEETS_LIST = "importedStyleSheets.txt";

                                       // map of class constructors           //
protected static final Map<String,Function> kFACTORY_MAP;

                                       // not doing rsrc embedding this way...//
//                                       // map of embedded resources whose     //
//                                       // values holds both text and bytes as //
//                                       // a UTF-8 string                      //
//protected static final Map<String,String>   kRESOURCE_MAP;

                                       // class variables ------------------- //
                                       // none                                //
                                       // public instance variables --------- //
                                       // (none)                              //
                                       // protected instance variables -------//
                                       // (none)                              //
                                       // private instance variables -------- //
                                       // (none)                              //
static
{
   kFACTORY_MAP = new HashMap<>();
//%factoryMapEntries%

                                       // not doing rsrc embedding this way...//
//   kRESOURCE_MAP = new HashMap<>();
////%resourceMapEntries%
}
/*------------------------------------------------------------------------------

@name       boot - application entry point
                                                                              */
                                                                             /**
            aApplication entry point.

@return     void

@param      classname      app class name

@history    Tue May 15, 2017 10:30:00 (Giavaneers - LBM) created

@notes
                                                                              */
//------------------------------------------------------------------------------
@JsMethod
public static ReactElement boot(
   String classname)
{
   return(
      ReactJava.boot(
         (AppComponentTemplate)Component.newInstance(classname, null)));
}
/*------------------------------------------------------------------------------

@name       getFactory - get factory for specified classname
                                                                              */
                                                                             /**
            Get factory for specified classname.

@return     factory for specified classname

@param      classname      specified classname

@history    Tue May 15, 2017 10:30:00 (Giavaneers - LBM) created

@notes
                                                                              */
//------------------------------------------------------------------------------
public static Function getFactory(
   String classname)
{
   return(kFACTORY_MAP.get(classname));
}
/*------------------------------------------------------------------------------

@name       getFactoryMap - get factory map
                                                                              */
                                                                             /**
            Get factory map.

@return     factory map

@history    Tue May 15, 2017 10:30:00 (Giavaneers - LBM) created

@notes
                                                                              */
//------------------------------------------------------------------------------
public static Map<String,Function> getFactoryMap()
{
   return(kFACTORY_MAP);
}
/*------------------------------------------------------------------------------

@name       getResource - get resource for specified name
                                                                              */
                                                                             /**
            Get resource for specified name.

@return     resource for specified name

@param      resourceName      specified name

@history    Wed Aug 19, 2020 10:30:00 (Giavaneers - LBM) created

@notes
                                                                              */
//------------------------------------------------------------------------------
                                       // not doing rsrc embedding this way...//
//public static Object getResource(
//   String resourceName)
//{
//   return(kRESOURCE_MAP.get(resourceName));
//}
/*------------------------------------------------------------------------------

@name       getResourceMap - get resource map
                                                                              */
                                                                             /**
            Get resource map.

@return     resource map

@history    Wed Aug 19, 2020 10:30:00 (Giavaneers - LBM) created

@notes
                                                                              */
//------------------------------------------------------------------------------
                                       // not doing rsrc embedding this way...//
//public static Map<String,String> getResourceMap()
//{
//   return(kRESOURCE_MAP);
//}
/*------------------------------------------------------------------------------

@name       getPlatformProvider - get platform provider to be injected
                                                                              */
                                                                             /**
            Get platform provider to be injected.

@return     platform provider to be injected

@history    Tue May 15, 2017 10:30:00 (Giavaneers - LBM) created

@notes
                                                                              */
//------------------------------------------------------------------------------
public static String getPlatformProvider()
{
   return("%platformProviderClassname%");
}
}//====================================// ReactGeneratedCode =================//
